Adding pg to peerDependencies
brianc/node-postgres pull request #2471
Opened 2021-02-13 03:47 UTC by ed0wolf

Yarn2 requires strict imports, I.E. all project dependencies need to exist in that project's package.json.

2021-02-13 05:04 UTC, charmander requested changes

2021-02-13 05:04 UTC, charmander commented on packages/pg-cursor/package.json
> +    "pg": ">=8.0"
I’m not sure if this should assume it’ll be compatible with a new major version of pg. If it turns out to be, a new release can always expand the range. So, `"pg": "^8"`?
```suggestion
    "pg": "^8"
```

2021-02-14 01:51 UTC, charmander approved these changes

2021-03-12 14:24 UTC, brianc commented
thanks! Sorry for the delay - had a bunch of stuff happen in my life all at once so I had to take a computer break for a few weeks.

2021-03-12 14:24 UTC, merged