Add Cursor to index.js's module.exports
brianc/node-postgres pull request #2550
Opened 2021-05-25 19:00 UTC by Bluenix2

Even though the documentation refers to it as [pg.Cursor](https://node-postgres.com/api/cursor) it isn't actually defined in the library's index.js.

I don't completely get the argument why it wasn't added in the first place, but I am going to guess that it's because not everyone uses Cursors. I thought this would be an alright compromise between that.

One downside with this change, is the somewhat unexpected behaviour one might experience if they try to use `pg.Cursor` without `pg-cursor` installed. Best way to fix that downside is to simply add `pg-cursor` to the dependencies, and include it like Pool, but this might be unwanted?

2021-05-25 19:54 UTC, charmander requested changes
I think it’d be better to fix the documentation instead. Even the way `pg.Pool` is included isn’t the cleanest, but it at least has a reason in that `pg.Pool` is a `Pool` type bound to `pg.Client` (i.e. it’s not exactly the same as the `Pool` you import from `pg-pool`).

2021-06-15 16:25 UTC, brianc commented
Thanks for doing this, but I agree with @charmander  I'd rather change the documentation than export the cursor in the main package.  It's an optional additional install & separate module.  

There's an argument to be made for including it and exporting it, but if that were the case I'd take a hard dependency on it so I could keep the versions locked together w/ the main `pg` package and `pg-cursor`.

2021-06-15 16:25 UTC, closed without merging

2021-06-15 20:29 UTC, Bluenix2 commented
> There's an argument to be made for including it and exporting it, but if that were the case I'd take a hard dependency on it so I could keep the versions locked together w/ the main `pg` package and `pg-cursor`.
@brianc

Is there a reason for this not to be done so far? I suppose it's not as widely used?

2021-06-16 16:44 UTC, brianc commented
yeah it's not as widely used and allows revving a major semver on the
cursor lib w/o having to do a major semver of pg as a whole.  I think the
thing pg-cursor is likely most widely used for is actually pg-query-stream
(which uses it internally).


On Tue, Jun 15, 2021 at 3:29 PM Bluenix ***@***.***> wrote:

> There's an argument to be made for including it and exporting it, but if
> that were the case I'd take a hard dependency on it so I could keep the
> versions locked together w/ the main pg package and pg-cursor.
> @brianc <https://github.com/brianc>
>
> Is there a reason for this not to be done so far? I suppose it's not as
> widely used?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/brianc/node-postgres/pull/2550#issuecomment-861809713>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMHINRLQRR2WLPR3OEOWDTS6Z2HANCNFSM45P76KHA>
> .
>