Add a Chinese cryptography algorithm, its name is SM3, currently used…
brianc/node-postgres pull request #2663
Opened 2021-11-30 09:42 UTC by w345731923

… by many Chinese database companies. Later I will submit the use in /pg.Similar to MD5.

2021-12-01 08:42 UTC, charmander commented
I don’t think support for this should be added.

2021-12-06 12:16 UTC, darkgl0w requested changes
As @charmander I think that support for this should not be added.

2021-12-13 02:08 UTC, adam-nielsen commented
Apparently SM3 is an open standard and based on the NSA's SHA-2 algorithm, and offers similar security to SHA-256.  I've done some cursory investigation and it appears that there aren't any security issues around it, however it also doesn't appear to have been widely investigated.  It would be interesting to see if someone like the NSA has reviewed it and what their opinion of it is.  At any rate, this PR only proposes using the SM3 algorithm for authentication, which does not appear to be a cause for concern as it would only be used if you configured your PG server to also use SM3.

However it does concern me that the algorithm implementation is pulled in from an external library with quite a small user base, as this increases the risk of unauthorised code injection.  If SM3 support is to be added (which I have no problem with), I think it would be more secure to include the algorithm implementation as part of the PR itself, to avoid pulling in another external library that is not under the control of the existing node-postgres maintainers.

2021-12-13 02:09 UTC, adam-nielsen commented on packages/pg/package.json
> -    "pg-protocol": "^1.5.0",
How come `pg-protocol` is being removed?  Don't you need this for the new algorithm that has been added?

2021-12-13 03:10 UTC, w345731923 commented
I agree with you,SM3 Code 13 May not be universal, at least for now.

2021-12-13 03:10 UTC, closed without merging

2021-12-26 05:19 UTC, brianc commented
> However it does concern me that the algorithm implementation is pulled in from an external library with quite a small user base, as this increases the risk of unauthorised code injection. If SM3 support is to be added (which I have no problem with), I think it would be more secure to include the algorithm implementation as part of the PR itself, to avoid pulling in another external library that is not under the control of the existing node-postgres maintainers.

100% agree with this. Thank you!