eslint: enable recommended ruleset
brianc/node-postgres pull request #3263
Opened 2024-06-19 15:53 UTC by alxndrsn

2025-02-19 09:34 UTC, alxndrsn commented
@brianc is there anything I can do to help get this PR considered for review?

2025-02-20 01:37 UTC, charmander commented
I’d merge this if it were just the ESLint rule. Don’t want to combine two unrelated changes.

2025-02-20 01:37 UTC, charmander requested changes
I’d merge this if it were just the ESLint rule. Don’t want to combine two unrelated changes.

2025-02-20 07:42 UTC, alxndrsn commented
> I’d merge this if it were just the ESLint rule. Don’t want to combine two unrelated changes.

Thanks for the feedback.  I've reverted the unrelated changes.

2025-03-04 23:29 UTC, charmander approved these changes

2025-03-06 00:29 UTC, charmander commented
Oh, I see there are no code changes associated with this. How about applying the entire ESLint recommended configuration, then?

2025-04-06 14:57 UTC, alxndrsn commented
> How about applying the entire ESLint recommended configuration, then?

I've done this, and updated the PR title to reflect the change.

Eslint's ECMAScript version is bumped to 2020 as this was required to support `globalThis` (already in use before this PR), and [2020 seems to be fully supported by node 16](https://compat-table.github.io/compat-table/es2016plus/), which is the oldest version supported in this repo's CI tests:

https://github.com/brianc/node-postgres/blob/a9fd34fb4217a7c16f02a4726efd61ad6a4f4796/.github/workflows/ci.yml#L40-L45

It's picked up some obvious errors, and some stuff which is more debatable.

2025-04-08 10:13 UTC, charmander requested changes
Thank you! I see lots of important improvements here.

2025-04-08 10:13 UTC, charmander commented on packages/pg-pool/test/idle-timeout-exit.js
> -    done()
I haven’t really looked at this, but there’s probably more to do here than quietly deleting a line. Does none of this code run at all, then?

2025-04-08 10:13 UTC, charmander commented on packages/pg/bench.js
> +  } while (Date.now() - start > time)
The logic here has been inverted.

2025-04-08 10:13 UTC, charmander commented on packages/pg/bench.js
> +  } while (Date.now() - start > time)
The logic here has been inverted.

2025-04-08 10:13 UTC, charmander commented on packages/pg/lib/crypto/cert-signatures.js
> +  let lastIndex = index + OIDLength
Yikes! Good catch.

2025-04-08 10:13 UTC, charmander commented on packages/pg/test/unit/client/sasl-scram-tests.js
> +              0x2a, // OID: 1.2.840.113549.1.1.11 (RSASSA-PKCS1-v1_5 / SHA-256)
(note for other readers: the difference is a zero-width space after “SHA-256”)

2025-04-08 10:15 UTC, charmander commented
> Eslint's ECMAScript version is bumped to 2020 as this was required to support `globalThis` (already in use before this PR), and [2020 seems to be fully supported by node 16](https://compat-table.github.io/compat-table/es2016plus/), which is the oldest version supported in this repo's CI tests:

You can define `navigator` as a global instead. Despite the lack of CI, pg 8 still supports Node 8(!).

2025-04-11 08:11 UTC, alxndrsn commented on packages/pg/bench.js
> +  } while (Date.now() - start > time)
I don't think the logic has been changed?  just changed to a more natural syntax:
```js
do { ... } while(condition) return x;
```
vs previous
```js
while(true) { ...; if(condition) return x; }
```

Code changes could be minimised by using `// eslint-disable-next-line no-constant-condition` if that's preferred.

2025-04-11 08:18 UTC, charmander commented on packages/pg/bench.js
> +  } while (Date.now() - start > time)
Exiting a loop when *P* is the opposite of continuing a loop while *P*.

2025-04-11 08:19 UTC, alxndrsn commented on packages/pg/lib/crypto/cert-signatures.js
> +  let lastIndex = index + OIDLength
Could implications of this be interesting?  `lastIndex` might be scoped at the file/module level currently, but maybe safe in practice?

2025-04-11 08:21 UTC, charmander commented on packages/pg/lib/crypto/cert-signatures.js
> +  let lastIndex = index + OIDLength
I haven’t run it to check, but I assume it’s just leaking to the global object because the module isn’t in strict mode.

2025-04-11 08:25 UTC, alxndrsn commented on packages/pg/bench.js
> +  } while (Date.now() - start > time)
:facepalm: of course it is

2025-04-11 08:31 UTC, alxndrsn commented on packages/pg/bench.js
> +  } while (Date.now() - start > time)
reverted, and added lint exception

2025-04-11 08:38 UTC, alxndrsn commented
> You can define `navigator` as a global instead. Despite the lack of CI, pg 8 still supports Node 8(!).

Any thoughts on what to do with the existing `globalThis` in `packages/pg/lib/crypto/utils-webcrypto.js`?  From the filename, maybe it doesn't get used in node, so a specific exception would be ok?

2025-04-12 08:16 UTC, charmander approved these changes

2025-04-12 08:16 UTC, charmander commented on packages/pg-pool/test/idle-timeout-exit.js
> -    done()
My mistake! This is correct.

2025-04-12 08:17 UTC, merged